export const MIN_WINDOW_WIDTH = 960
export const SECOND_MIN_WINDOW_WIDTH = 520
export const MIN_WINDOW_HEIGHT = 600
export const DEFAULT_MINIWINDOW_WIDTH = 550
export const DEFAULT_MINIWINDOW_HEIGHT = 400
